### ISSUE TITLE
Can't get the application to run at all

### ISSUE THREAD

**Issue by SvbZ3r0** [NathanVaughn/webtrees-docker#103]
I'm unsure if the issue is with Webtrees or with the container or with me.

https://github.com/fisharebest/webtrees/issues/4473

**Comment by NathanVaughn** [comment]
Thanks, downgrade to 2.1.4 for the time being, I will look into this

**Comment by NathanVaughn** [comment]
It looks like the named tags of `2.1.4` and `2.1.5` are fine, but for some reason the `latest` tag got broken, and is still pointing to `2.0.24`. And the `2.0.x` versions of webtrees don't like php 8, hence it doesn't work.

**Comment by NathanVaughn** [comment]
This should be fixed now by https://github.com/NathanVaughn/webtrees-docker/commit/e5bce827775889bcbdfb236608a33c6da346cd76 and re-publishing 2.1.5 and 2.0.24

**Comment by SvbZ3r0** [comment]
Thanks for the quick update! I think the `latest` tag is still broken because it still shows the same error but the `2.1.5` tag doesn't. But that might be a caching issue.

I still can't get it to work however. I'll be the first to admit I don't know a peep about getting docker to work well. I'm on unRaid, and all the popular containers come with templates, so I haven't had a problem before.
Would you mind taking a look at my configuration and telling me what I'm doing that is wrong.

I am currently getting a HTTP 500 instead of the Fatal Error that I got before.

**Comment by NathanVaughn** [comment]
I think you just need to repull the `latest` tag, I pulled `ghcr.io/nathanvaughn/webtrees:latest` and it works fine.

As for the other issues, my best guess is that because the application was erroring out, while in the middle of the setup, it ended up in a corrupted state. I ran the example `docker-compose.yml` file and had no problems. If you haven't loaded much real data in, you may want to try clearing everything and starting fresh.

**Comment by SvbZ3r0** [comment]
I ended up taking a backup of all the data I entered and tried to start from scratch.
What I noticed is that the Setup wizard only runs automatically if a config file doesn't already exist.
https://github.com/NathanVaughn/webtrees-docker/blob/e5bce827775889bcbdfb236608a33c6da346cd76/docker-entrypoint.py#L200-L235
I do not know if this is intended behaviour, but since a config file was present for me from previous installs, the setup wizard didn't trigger.

So I went ahead, deleted the config file and tried again. This time (and every consecutive time that I tried), it failed here:
https://github.com/NathanVaughn/webtrees-docker/blob/e5bce827775889bcbdfb236608a33c6da346cd76/docker-entrypoint.py#L262-L282
with a `ConnectionRefusedError: [Errno 111] Connection refused`.

Any idea why this might be happening?

**Comment by NathanVaughn** [comment]
Sorry I haven't gotten a chance to look at this until now.

Only running the setup wizard if a config file doesn't exist is deliberate, yes. The webtrees setup wizard is what creates that config file, and does some database initialization, and once that's done, there's no way to get back to it.

I don't know why the connection would be refused. The Apache server will have already started on a generic HTTP-only config such that the Python script can send that request to trigger the first-time setup. I've had 0 issues with it when running from a blank slate.

Running the `docker-compose` file in the repo:
![image](https://user-images.githubusercontent.com/8636459/173973181-5c18b17c-e1dd-4709-88b6-3b6b753d77fe.png)
You can see at the bottom the request gets sent and accepted.

I also tried a different database type

```yml
      DB_TYPE: "sqlite"
      DB_NAME: "webtrees"
```

and no issues again.

**Comment by SvbZ3r0** [comment]
This is extremely weird. My logs are, word for word, same as yours. But the issue is 100% reproduceable on my end. Pretty ironic considering Docker is supposed to fix exactly this issue XD
Anyway.. I'm using a different container now since that one doesn't cause me any issues. 
However, if there's any way I can assist in testing and debugging this, let me know and I'll be happy to help.
